### ISSUE TITLE
Is there way to encrypt LDAP password ? (at least Base 64)

### ISSUE THREAD

**Issue by gredwhite** [pingidentity/ldapsdk#159]
In my spring boot application I have following configuration for LDAP
```
ldap:
  connection:
    host: 123.45.67.89
    port: 389
    user: CN=Administrator,CN=Users,DC=MYCOMPANY,DC=COM
    password: SuPeRsEcrEt123#
```

Is there way to encrypt LDAP password ? at least Base64
